# Generated by Django 5.0.7 on 2024-08-10 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0004_alter_profile_bio_alter_profile_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
